# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -i https://pypi.gurobi.com gurobipy
        python -m pip install git+https://github.com/johwiebe/rogp.git
        sudo apt-get install libopenblas-dev gfortran liblapack-dev glpk-utils
    - name: Setup TPL package directories
            run: |
              TPL_DIR="${GITHUB_WORKSPACE}/cache/tpl"
              mkdir -p "$TPL_DIR"
              DOWNLOAD_DIR="${GITHUB_WORKSPACE}/cache/download"
              mkdir -p "$DOWNLOAD_DIR"
              echo "TPL_DIR=$TPL_DIR" >> $GITHUB_ENV
              echo "DOWNLOAD_DIR=$DOWNLOAD_DIR" >> $GITHUB_ENV
    - name: Install Ipopt
      run: |
        IPOPT_DIR=$TPL_DIR/ipopt
        echo "$IPOPT_DIR" >> $GITHUB_PATH
        mkdir -p $IPOPT_DIR
        IPOPT_TAR=${DOWNLOAD_DIR}/ipopt.tar.gz
        if test ! -e $IPOPT_TAR; then
            echo "...downloading Ipopt"
            URL=https://github.com/IDAES/idaes-ext
            RELEASE=$(curl --max-time 150 --retry 8 \
                -L -s -H 'Accept: application/json' ${URL}/releases/latest)
            VER=$(echo $RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
            URL=${URL}/releases/download/$VER
            curl --max-time 150 --retry 8 \
                -L $URL/idaes-solvers-ubuntu1804-64.tar.gz \
                > $IPOPT_TAR
        fi
        cd $IPOPT_DIR
        tar -xzi < $IPOPT_TAR
        echo ""
        echo "$IPOPT_DIR"
        ls -l $IPOPT_DIR

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m unittest discover -s romodel/tests
